### ISSUE TITLE
japkit-examples do not compile with JDK 11

### ISSUE THREAD

**Issue by vkennke** [japkit/japkit#30]
Oracle JDK 11 build 22

<pre><code>Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project japkit-examples-freebuilder: Compilation failure: Compilation failure: 
/C:/Develop/japkit-examples/japkit-examples-freebuilder/target/src/main/generated-sources/de/japkit/examples/freebuilder/FreeBuilderTemplate_RuntimeMetadata.java:[69,91] no interface expected here
/C:/Develop/japkit-examples/japkit-examples-freebuilder/target/src/main/generated-sources/de/japkit/examples/freebuilder/FreeBuilderTemplate_RuntimeMetadata.java:[69,195] repeated interface
Error during error reporting: java.lang.NullPointerException, cause:  
   	jdk.compiler/com.sun.tools.javac.model.JavacElements.doGetElement(JavacElements.java:175)
		jdk.compiler/com.sun.tools.javac.model.JavacElements.doGetTypeElement(JavacElements.java:170)
		jdk.compiler/com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:158)
		jdk.compiler/com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:85)
		de.japkit.services.ElementsExtensions.getTypeElement(ElementsExtensions.java:1702)
		de.japkit.services.MessageCollector.lambda$printAllMessages$4(MessageCollector.java:182)
		java.base/java.lang.Iterable.forEach(Iterable.java:75)
		de.japkit.services.MessageCollector.printAllMessages(MessageCollector.java:311)
		de.japkit.processor.JapkitProcessor.printAllErrors(JapkitProcessor.java:765)
		de.japkit.processor.JapkitProcessor.process(JapkitProcessor.java:204)
		jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:972)
		jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:808)
		jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1212)
		jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1347)
		jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
		jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
		jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
		jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
		jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
		jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
Type de.japkit.metaannotations.classselectors.None not found when writing source file for de.japkit.examples.freebuilder.FreeBuilderTemplate_RuntimeMetadata Missing type: de.japkit.metaannotations.classselectors.None
Type de.japkit.metaannotations.classselectors.None not found when writing source file for de.japkit.examples.freebuilder.FreeBuilderTemplate_RuntimeMetadata Missing type: de.japkit.metaannotations.classselectors.None   
/C:/Develop/japkit-examples/japkit-examples-freebuilder/src/main/java/de/japkit/examples/freebuilder/FreeBuilderTemplate.java:[34,8] Type de.japkit.metaannotations.classselectors.None not found when writing source file for de.japkit.examples.freebuilder.FreeBuilderTemplate_RuntimeMetadata Missing type: de.japkit.metaannotations.classselectors.None MetaElement: , MetaAnnotation: , Src: 
Type de.japkit.metaannotations.classselectors.None not found when writing source file for de.japkit.examples.freebuilder.FreeBuilderTemplate_RuntimeMetadata Missing type: de.japkit.metaannotations.classselectors.None MetaElement: , MetaAnnotation: , Src:  de.japkit.examples.freebuilder.FreeBuilderTemplate
</code></pre>

**Comment by stefanocke** [comment]
http://hg.openjdk.java.net/jdk/jdk11/file/d2e182aa44c9/src/jdk.compiler/share/classes/com/sun/tools/javac/model/JavacElements.java#l175

**Comment by stefanocke** [comment]
https://travis-ci.org/japkit/japkit-examples/builds/403684098

**Comment by stefanocke** [comment]
The reason is that Type.classType now implements ErrorType. So, every isntanceof check for ErrorType is wrong and must be fixed:
http://hg.openjdk.java.net/jdk/jdk11/file/d2e182aa44c9/src/jdk.compiler/share/classes/com/sun/tools/javac/code/Type.java#l933

Similar to https://github.com/japkit/japkit/issues/23 (Most instance of have been replaced there by type visitors, but obviously some are left)

**Comment by stefanocke** [comment]
The original error has been fixed. However, the petclinic example doe not build due to:

Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.5:war (default-war) on project japkit-examples-roo-petclinic: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.5:war failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-war-plugin:2.5:war: java.lang.ExceptionInInitializerError: null

**Comment by stefanocke** [comment]
Petclinic is quick-fixed now (Upgrade to Spring Boot 2.0.3. Builds but does not run yet.)
Javac Build are okay now.
JDT / Java 11 does not work, probabley not yet supported in tycho.

https://travis-ci.org/japkit/japkit-examples/builds/403872462

**Comment by stefanocke** [comment]
@vkennke , please give the current 1.16-SNAPSHOT a try

**Comment by vkennke** [comment]
It compiles with JDK 11, with target and source 1.8 as well as with target and source 11.
