### ISSUE TITLE
japkit does not compile with Java 11

### ISSUE THREAD

**Issue by stefanocke** [japkit/japkit#41]
... waits for https://github.com/eclipse/xtext/issues/1182

**Comment by cdietrich** [comment]
@stefanocke is this a with or a against?

**Comment by stefanocke** [comment]
@cdietrich , thanks for asking. I am not actually sure about the precise meaning of with vs against, so I describe steps to reproduce instead ;-)

1. Clone japkit
2. Run mvn clean install with a Java Home pointing to a JDK 11
3. See lots of exceptions in log

To be clear: I don't change source or target level in the pom to 11. It ist still 8.

**Comment by cdietrich** [comment]
it works fine for me with Xtext 2.16 as expected.
- you have to update maven javadoc plugin too.
- you have to deal with the removed javax.annotation.*

**Comment by stefanocke** [comment]
@cdietrich  thank you for this helpful hints! Will try asap. 
I think I mainly matched your "Xtext should not "explode" with Java 11" to my experience when switching to JDK 11. That's why I assumed I should wait for eclipse/xtext#1182 before trying again.

**Comment by cdietrich** [comment]
Xtext 2.16 is with java 11 against target<=10
Xtext 2.17 will work with java 11 target to

**Comment by stefanocke** [comment]
After upgrading to xtend 2.16 it builds with Oracle JDK 11: https://travis-ci.org/japkit/japkit/jobs/471320344
