### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [japkit/japkit#54]
Hello Japkit team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Japkit project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by stefanocke** [comment]
```
<tr>
	<td><a href="https://github.com/japkit/japkit">japkit</a></td>
	<td>Japkit is an annotation processor that allows to develop Java code generators by using code templates written in Java with some annotations. There is no need to write any imperative code, which makes the code generators short and concise and so eases their maintenance.</td>
	<td>Apache 2 License</td>
	<td>Tool</td>
	<td>Stefan Ocke</td>
</tr>

```

**Comment by miklossy** [comment]
Thank you @stefanocke !

**Comment by miklossy** [comment]
The `japkit` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).

**Comment by stefanocke** [comment]
@miklossy , thank you!
